// SignDrop — bilingual content dictionary (RU / EN). Verbatim from the content plans.
window.SD = {
  ru: {
    code: "ru",
    nav: { how: "Как", features: "Фичи", privacy: "Локально", compare: "Плюсы", download: "Скачать", github: "GitHub", tryOnline: "Попробовать онлайн", support: "Поддержать проект" },
    hero: {
      badge: "v1.1 · ОТКРЫТЫЙ КОД · LOCAL-FIRST",
      h1a: "Подпишите любой документ",
      h1b: "за пару секунд",
      sub: "PDF, JPEG, PNG, TIFF, WEBP. Подпись накладывается прямо на вашем устройстве.",
      btnWin: "Скачать для Windows",
      btnMac: "Скачать для Mac",
      btnLinux: "Скачать для Linux",
      btnDocker: "Запустить через Docker",
      btnDemo: "Попробовать онлайн",
      allPlatforms: "Все платформы",
      hint: "Подвигай курсор — оставь росчерк",
    },
    facts: ["100% локально", "Бесплатно", "Web + Desktop"],
    factsIcons: ["lock", "free", "monitor"],
    osNote: "Windows · macOS · Linux",
    how: {
      title: "Как это работает",
      kicker: "ОТ ДОКУМЕНТА ДО ПОДПИСИ",
      steps: [
        { n: "01", t: "Загрузите документ", d: "Откройте PDF, JPEG, PNG, TIFF или WEBP. Файл открывается прямо в браузере.", m: "ПРИНИМАЕТ: .pdf · .jpg · .png · .tiff · .webp" },
        { n: "02", t: "Добавьте подпись", d: "Загрузите фото или скан своей подписи. Фон удаляется автоматически.", m: "УДАЛЕНИЕ ФОНА: АВТО" },
        { n: "03", t: "Перетащите на нужное место", d: "Точное позиционирование, изменение размера, поворот.", m: "ХОЛСТ: ПЕРЕМЕЩЕНИЕ · РАЗМЕР · ПОВОРОТ" },
        { n: "04", t: "Сохраните результат", d: "Скачайте подписанный документ. Файл не покидает устройство.", m: "ЭКСПОРТ: .pdf · .jpeg · ЛОКАЛЬНО" },
      ],
    },
    features: {
      title: "Работает чисто и качественно",
      kicker: "ВОЗМОЖНОСТИ",
      note: "БЕЗ ОБЛАКОВ · БЕЗ РЕГИСТРАЦИИ · БЕЗ ТРЕКЕРОВ",
      flagTag: "01 / КЛЮЧЕВЫЕ ФУНКЦИИ",
      flagTitle: "100% локально.",
      flagTitle2: "Ноль контактов с серверами.",
      flagDesc: "Документы и подписи никогда не покидают устройство. Можно вырубить интернет — всё работает.",
      flagMetric: "УШЛО НА СЕРВЕРЫ",
      items: [
        { tag: "02 / ФОРМАТЫ", t: "Все форматы документов", d: "PDF (одно- и многостраничные), JPEG, PNG, TIFF, WEBP до 50 МБ.", chips: [".pdf", ".jpg", ".png", ".tiff", ".webp"] },
        { tag: "03 / УДАЛЕНИЕ ФОНА", t: "Авто-удаление фона", d: "Загружайте подпись с любого фона — белого, в клетку, размытого. Алгоритм оставит только росчерк.", mono: "УДАЛЕНИЕ ФОНА: АВТО · ОФЛАЙН" },
        { tag: "04 / БИБЛИОТЕКА", t: "Библиотека подписей", d: "Сохраните несколько подписей — личную, рабочую, инициалы. Всё хранится локально в браузере." },
        { tag: "05 / РАЗМЕЩЕНИЕ", t: "Подпись в нужном месте", d: "Точное позиционирование, изменение размера, поворот, прозрачность. Размещение с точностью до пикселя.", mono: "ХОЛСТ: ПЕРЕМЕЩЕНИЕ · РАЗМЕР · ПОВОРОТ · ПРОЗРАЧНОСТЬ" },
        { tag: "06 / МНОГОСТРАНИЧНОСТЬ", t: "Многостраничный PDF", d: "Своя подпись на каждой странице или «применить ко всем» одной кнопкой." },
        { tag: "07 / УНИКАЛИЗАЦИЯ", t: "Уникализация подписи", d: "Каждое наложение чуть отличается — наклон, пропорции. Как настоящая подпись, не штамп." },
        { tag: "08 / ЭКСПОРТ", t: "Экспорт без потерь", d: "Сохраняется в PDF и JPEG. Оригинальный файл не изменяется." },
        { tag: "09 / ПОДСКАЗКИ", t: "Пошаговые подсказки", d: "Сайдбар ведёт по шагам, активный шаг подсвечен." },
      ],
      killer: { tag: "10 / РУКОПИСНЫЙ ТЕКСТ", t: "Рукописный текст вместе с подписью", d: "Добавьте не только подпись, но и рукописный текст — например, дату или пометку — прямо в документе.", badge: "НОВОЕ" },
    },
    privacy: {
      kicker: "ПРИВАТНОСТЬ",
      title: "Ваши документы — только ваши",
      text: "SignDrop не отправляет файлы на сервер. Вообще никогда. Подпись обрабатывается прямо в браузере или нативном приложении — ни документ, ни подпись не покидают ваш компьютер.",
      chips: "Приватность в приоритете · Без сбора данных · Без облака",
      metric: "0 байт ушло на серверы",
      flow: ["файл", "SignDrop", "готово"],
      cloud: "облако",
      cloudNote: "никогда",
    },
    compare: {
      kicker: "БЕНЧМАРКИ",
      title: "Где SignDrop сильнее", vs: "VS", other: "другие сервисы",
      cols: ["SignDrop", "Chrome", "DocuSign", "Adobe Sign", "SmallPDF"],
      rows: [
        { label: "Загружает файлы на сервер", vals: ["never", "no", "yes", "yes", "yes"], invert: true, neverText: "Никогда" },
        { label: "Бесплатно", vals: ["yes", "yes", "no", "no", "partial"] },
        { label: "Без регистрации", vals: ["yes", "yes", "no", "no", "no"] },
        { label: "Рукописная подпись (фото/скан)", vals: ["yes", "drawonly", "yes", "yes", "yes"] },
        { label: "Форматы", vals: ["PDF, JPG, PNG, TIFF, WEBP", "PDF", "PDF", "PDF", "PDF, JPG"], text: true },
        { label: "Библиотека подписей", vals: ["yes", "no", "yes", "yes", "no"] },
        { label: "Удаление фона", vals: ["autoyes", "no", "no", "no", "no"] },
        { label: "Многостраничный PDF", vals: ["yes", "no", "yes", "yes", "no"] },
        { label: "Работает офлайн", vals: ["yes100", "partial", "no", "no", "no"] },
        { label: "Windows-приложение", vals: ["yes", "no", "no", "no", "no"] },
        { label: "Открытый исходный код", vals: ["yes", "no", "no", "no", "no"] },
      ],
      footer: "SignDrop — настоящая подпись как на бумаге, с библиотекой, офлайн, на любом формате. Круче, чем в Chrome!",
      labels: { drawonly: "Только рисовать", partial: "Частично" },
    },
    demo: {
      kicker: "ВСЁ ВНУТРИ",
      title: "Полный контроль",
      text: "Пользуйтесь SignDrop прямо в браузере: документы и подписи обрабатываются локально, ничего не уходит на сервер, а исходники открыты для проверки.",
      bullets: [
        "Подписи и рукописный текст остаются у вас.",
        "Можно ставить дату от руки прямо в документе.",
        "Никаких скрытых загрузок и утечек.",
        "Всё прозрачно и локально.",
      ],
      killerIdx: 1,
      killerBadge: "НОВОЕ",
      cta: "Попробовать онлайн",
    },
    download: {
      kicker: "СКАЧАТЬ / ЗАПУСТИТЬ",
      title: "Установите за минуту",
      crossNote: "Нативные сборки для всех систем",
      usersTitle: "Для пользователей",
      devsTitle: "Для разработчиков",
      os: [
        { id: "win", icon: "windows", name: "Windows", sub: ".exe · установщик", link: "exe" },
        { id: "mac", icon: "apple", name: "macOS", sub: ".dmg · Intel + Apple Silicon", link: "mac" },
        { id: "linux", icon: "linux", name: "Linux", sub: ".deb · .rpm", link: "linux" },
      ],
      dockerTitle: "Запустить через Docker",
      dockerSub: "Одна команда — и готово",
      ghTitle: "Исходный код на GitHub",
      ghSub: "MIT · форкайте, вносите вклад",
      badgeVer: "v1.1.2",
      badgeLic: "MIT",
    },
    support: {
      kicker: "ПОДДЕРЖАТЬ ПРОЕКТ",
      title: "Классный софт, правда?",
      text: "SignDrop — бесплатный инструмент с открытым кодом. Если он сэкономил тебе время — поддержи разработку.",
      kofi: "CloudTips",
      yoomoney: "ЮMoney",
    },
    footer: {
      tagline: "Рукописная подпись. Локально, без облаков.",
      links: "Ссылки",
      docs: "Документы",
      linkTry: "Попробовать онлайн",
      linkGithub: "GitHub",
      linkDownload: "Скачать",
      linkSupport: "Поддержать",
      docPrivacy: "Политика конфиденциальности",
      docTerms: "Пользовательское соглашение",
      copyright: "© 2026 SignDrop · Сделано с помощью TAUSIK Core · Лицензия MIT · v1.1.2",
    },
    cookie: {
      text: "Мы используем Яндекс.Метрику для анализа посещаемости.",
      link: "Политика конфиденциальности",
      accept: "Принять",
    },
  },

  en: {
    code: "en",
    nav: { how: "How", features: "Features", privacy: "Local", compare: "Pros", download: "Download", github: "GitHub", tryOnline: "Try online", support: "Support project" },
    hero: {
      badge: "v1.1 · OPEN SOURCE · LOCAL-FIRST",
      h1a: "Sign any document",
      h1b: "in seconds",
      sub: "PDF, JPEG, PNG, TIFF, WEBP. Your signature is placed right on your device.",
      btnWin: "Download for Windows",
      btnMac: "Download for Mac",
      btnLinux: "Download for Linux",
      btnDocker: "Run via Docker",
      btnDemo: "Try online",
      allPlatforms: "All platforms",
      hint: "Move your cursor — leave a stroke",
    },
    facts: ["100% local", "Free", "Web + Desktop"],
    factsIcons: ["lock", "free", "monitor"],
    osNote: "Windows · macOS · Linux",
    how: {
      title: "How it works",
      kicker: "FROM DOCUMENT TO SIGNED",
      steps: [
        { n: "01", t: "Load your document", d: "Open a PDF, JPEG, PNG, TIFF or WEBP file. The file opens directly in your browser.", m: "ACCEPTS: .pdf · .jpg · .png · .tiff · .webp" },
        { n: "02", t: "Add your signature", d: "Upload a photo or scan of your handwritten signature. Background is removed automatically.", m: "BACKGROUND REMOVAL: AUTO" },
        { n: "03", t: "Drag it where you need", d: "Precise positioning, resize, rotate.", m: "CANVAS: MOVE · RESIZE · ROTATE" },
        { n: "04", t: "Save your document", d: "Download the signed file. The file never leaves your device.", m: "EXPORT: .pdf · .jpeg · LOCAL" },
      ],
    },
    features: {
      title: "Works cleanly and well",
      kicker: "FEATURES",
      note: "NO CLOUD · NO REGISTRATION · NO TRACKERS",
      flagTag: "01 / KEY FEATURES",
      flagTitle: "100% local.",
      flagTitle2: "Zero servers touched.",
      flagDesc: "Documents and signatures never leave your device. Turn off the internet — it still works.",
      flagMetric: "SENT TO SERVERS",
      items: [
        { tag: "02 / FORMATS", t: "All document formats", d: "PDF (single and multi-page), JPEG, PNG, TIFF, WEBP up to 50 MB.", chips: [".pdf", ".jpg", ".png", ".tiff", ".webp"] },
        { tag: "03 / BACKGROUND REMOVAL", t: "Auto background removal", d: "Upload a signature from any background — white, lined, blurry. The algorithm keeps only the handwriting.", mono: "BG_REMOVE: AUTO · OFFLINE" },
        { tag: "04 / LIBRARY", t: "Signature library", d: "Save multiple signatures — personal, work, initials. Everything is stored locally in your browser." },
        { tag: "05 / PLACEMENT", t: "Place it exactly where you need", d: "Precise positioning, resize, rotate, opacity. Pixel-perfect placement.", mono: "CANVAS: MOVE · RESIZE · ROTATE · OPACITY" },
        { tag: "06 / MULTI-PAGE", t: "Multi-page PDF", d: "A unique signature on each page, or apply to all with one click." },
        { tag: "07 / UNIQUIFICATION", t: "Signature uniquification", d: "Every placement is slightly different — tilt, proportions. Like a real signature, not a stamp." },
        { tag: "08 / EXPORT", t: "Lossless export", d: "Saves as PDF and JPEG. The original file stays untouched." },
        { tag: "09 / HINTS", t: "Step-by-step hints", d: "A sidebar guides you through; the active step is highlighted." },
      ],
      killer: { tag: "10 / HANDWRITTEN TEXT", t: "Handwritten text alongside your signature", d: "Add not just a signature but handwritten text — like a date or a note — right on the document.", badge: "NEW" },
    },
    privacy: {
      kicker: "PRIVACY",
      title: "Your documents belong only to you",
      text: "SignDrop never sends files to a server. Ever. Your signature is processed directly in the browser or native app — neither the document nor the signature ever leaves your computer.",
      chips: "Privacy first · No data collection · No cloud",
      metric: "0 bytes sent to servers",
      flow: ["file", "SignDrop", "done"],
      cloud: "cloud",
      cloudNote: "never",
    },
    compare: {
      kicker: "BENCHMARKS",
      title: "Where SignDrop wins", vs: "VS", other: "other tools",
      cols: ["SignDrop", "Chrome", "DocuSign", "Adobe Sign", "SmallPDF"],
      rows: [
        { label: "Uploads files to server", vals: ["never", "no", "yes", "yes", "yes"], invert: true, neverText: "Never" },
        { label: "Free", vals: ["yes", "yes", "no", "no", "partial"] },
        { label: "No registration", vals: ["yes", "yes", "no", "no", "no"] },
        { label: "Handwritten signature (photo/scan)", vals: ["yes", "drawonly", "yes", "yes", "yes"] },
        { label: "Formats", vals: ["PDF, JPG, PNG, TIFF, WEBP", "PDF", "PDF", "PDF", "PDF, JPG"], text: true },
        { label: "Signature library", vals: ["yes", "no", "yes", "yes", "no"] },
        { label: "Background removal", vals: ["autoyes", "no", "no", "no", "no"] },
        { label: "Multi-page PDF", vals: ["yes", "no", "yes", "yes", "no"] },
        { label: "Works offline", vals: ["yes100", "partial", "no", "no", "no"] },
        { label: "Windows app", vals: ["yes", "no", "no", "no", "no"] },
        { label: "Open source", vals: ["yes", "no", "no", "no", "no"] },
      ],
      footer: "SignDrop — a real signature like on paper, with a library, offline, any format. Better than Chrome.",
      labels: { drawonly: "Draw only", partial: "Partially" },
    },
    demo: {
      kicker: "ALL INSIDE",
      title: "Full control",
      text: "Use SignDrop right in your browser: documents and signatures are processed locally, nothing goes to a server, and the source is open to inspect.",
      bullets: [
        "Signatures and handwritten text stay with you.",
        "Add a handwritten date right on the document.",
        "No hidden uploads or leaks.",
        "Fully transparent and local.",
      ],
      killerIdx: 1,
      killerBadge: "NEW",
      cta: "Try online",
    },
    download: {
      kicker: "DOWNLOAD / RUN",
      title: "Set up in a minute",
      crossNote: "Native builds for every system",
      usersTitle: "For users",
      devsTitle: "For developers",
      os: [
        { id: "win", icon: "windows", name: "Windows", sub: ".exe · installer", link: "exe" },
        { id: "mac", icon: "apple", name: "macOS", sub: ".dmg · Intel + Apple Silicon", link: "mac" },
        { id: "linux", icon: "linux", name: "Linux", sub: ".deb · .rpm", link: "linux" },
      ],
      dockerTitle: "Run via Docker",
      dockerSub: "One command and you're done",
      ghTitle: "Source code on GitHub",
      ghSub: "MIT · fork it, contribute",
      badgeVer: "v1.1.2",
      badgeLic: "MIT",
    },
    support: {
      kicker: "SUPPORT THE PROJECT",
      title: "Nice software, right?",
      text: "SignDrop is a free open-source tool. If it saved you time — support the development.",
      kofi: "CloudTips",
      yoomoney: "YooMoney",
    },
    footer: {
      tagline: "Handwritten signatures. Local, no cloud.",
      links: "Links",
      docs: "Documents",
      linkTry: "Try online",
      linkGithub: "GitHub",
      linkDownload: "Download",
      linkSupport: "Support",
      docPrivacy: "Privacy Policy",
      docTerms: "Terms of Service",
      copyright: "© 2026 SignDrop · Made with TAUSIK Core · MIT License · v1.1.2",
    },
    cookie: {
      text: "We use Yandex.Metrica to analyze site traffic.",
      link: "Privacy Policy",
      accept: "Accept",
    },
  },
};

window.SD_LINKS = {
  demo: "https://signdrop.tinacodes.space/",
  github: "https://github.com/TinaUma/signdrop",
  exe: "https://github.com/TinaUma/signdrop/releases/download/v1.1.2/SignDrop_1.1.2_x64-setup.exe",
  mac: "https://github.com/TinaUma/signdrop/releases/download/v1.1.2/SignDrop_1.1.2_aarch64.dmg",
  linux: "https://github.com/TinaUma/signdrop/releases/download/v1.1.2/SignDrop_1.1.2_amd64.deb",
  releases: "https://github.com/TinaUma/signdrop/releases",
  docker: "git clone https://github.com/TinaUma/signdrop.git && cd signdrop && docker compose up",
  kofi: "https://pay.cloudtips.ru/p/ea5537e6",
  yoomoney: "https://yoomoney.ru/to/4100119540100972",
  privacy: "privacy.html",
  terms: "terms.html",
};
